Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.hostname = "sensu-enterprise-sandbox"
  config.vm.network "private_network", ip: "172.31.255.3"
  config.vm.provision "shell",
    env: {
      "SE_USER" => ENV["SE_USER"],
      "SE_PASS" => ENV["SE_PASS"]
    },
    path: "sensu-and-influx.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end
