require "net/http"

def url_exist?(url_string,user,pass)
  uri = URI.parse(url_string)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = (uri.scheme == 'https')
  req = Net::HTTP::Head.new(uri.request_uri)
  req.basic_auth(user,pass)
  res = http.request(req)
  res.code == "200" # false if return 200
rescue Errno::ENOENT
  false # false if can't find the server
end


Vagrant.configure("2") do |config|
  envvars = { }

  sandbox_type = "core"

  envvars["SENSU_SANDBOX_TYPE"] = sandbox_type

  config.vm.define "sensu-go-sandbox-x86-64", default: true, autostart: true do |sandbox|
    # Bento centos7 box 
    sandbox.vm.box = "bento/centos-7"

    sandbox.vm.hostname = "sensu-go-sandbox" 

    # Support virtualbox provider
    sandbox.vm.provider "virtualbox" do |vb, vboxoverride|
      vb.cpus = 2
      vb.memory = 2048
      vb.name = "sensu-go-sandbox-x86-64"
    end
    
    # Create forwarded port mapping which allows host access to specific sandbox ports
    #Forward Sensu backend APIs
    sandbox.vm.network "forwarded_port", guest: 2379, host: 2379
    sandbox.vm.network "forwarded_port", guest: 2380, host: 2380
    sandbox.vm.network "forwarded_port", guest: 8080, host: 8080
    sandbox.vm.network "forwarded_port", guest: 8081, host: 8081

    # Forward Sensu Dashboard to localhost 3000 
    sandbox.vm.network "forwarded_port", guest: 3000, host: 3000
    # Forward Grafana Dashboard to localhost 4000 
    sandbox.vm.network "forwarded_port", guest: 4000, host: 4000

    if ENV['SHARED_SENSU_DIR']
      if File.directory?(ENV['ENABLE_SHARED_SENSU_DB']) 
        sandbox.vm.synced_folder ENV['SHARED_SENSU_DIR'], "/var/lib/sensu"
      else
        puts "Shared Dir is invalid"
        abort
      end
      envvars["SHARED_SENSU_DIR"] = ENV['SHARED_SENSU_DIR'] 
    end

    sandbox.vm.synced_folder "./files", "/vagrant_files"
    sandbox.vm.synced_folder "./lesson_plans", "/lesson_plans"
    sandbox.vm.provision :shell do |s|
      envars||={}
      envvars['SANDBOX_LESSON']=ENV['SANDBOX_LESSON']
      s.env = envvars
      s.path = "./provision/setup.sh"
    end
  end
end
