require "net/http"

def url_exist?(url_string,user,pass)
  uri = URI.parse(url_string)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = (uri.scheme == 'https')
  req = Net::HTTP::Head.new(uri.request_uri)
  req.basic_auth(user,pass)
  res = http.request(req)
  res.code == "200" # false if return 200
rescue Errno::ENOENT
  false # false if can't find the server
end


Vagrant.configure("2") do |config|
  envvars = { }

  sandbox_type = "core"
  # Enterprise
  if ENV['SE_USER'] &&  ENV['SE_PASS']
    envvars["SE_USER"] = ENV['SE_USER']
    envvars["SE_PASS"] = ENV['SE_PASS']
    url = "http://enterprise.sensuapp.com/yum/noarch/repodata/repomd.xml"
    unless url_exist?(url,ENV['SE_USER'],ENV['SE_PASS'])
      puts "Your Sensu Enterprise credentials appear to be invalid,\nor you have a networking problem preventing access to the Enterprise repository.\nPlease confirm your SE_USER and SE_PASS credentials are correct."
      abort
    end
    sandbox_type = "enterprise"
  end 
  envvars["SENSU_SANDBOX_TYPE"] = sandbox_type

  config.vm.define "sensu-sandbox-x86-64", default: true, autostart: true do |sandbox|
    # Bento centos7 box 
    sandbox.vm.box = "bento/centos-7"

    sandbox.vm.hostname = "sensu-sandbox" 

    # Support virtualbox provider
    sandbox.vm.provider "virtualbox" do |vb, vboxoverride|
      vb.cpus = 2
      vb.memory = 2048
      vb.name = "sensu-sandbox-x86-64"
    end
    
    # Create forwarded port mapping which allows host access to specific sandbox ports
    if ENV['ENABLE_SENSU_SANDBOX_PORT_FORWARDING'] 
      # Forward Sensu API and redis transport to localhost
      sandbox.vm.network "forwarded_port", guest: 6379, host: 6379
      sandbox.vm.network "forwarded_port", guest: 4567, host: 4567
      # Forward Sensu Dashboard to localhost 3001
      sandbox.vm.network "forwarded_port", guest: 3000, host: 3000
      # Forward Grafana Dashboard to localhost 3001
      sandbox.vm.network "forwarded_port", guest: 4000, host: 4000
      envvars["ENABLE_SENSU_SANDBOX_PORT_FORWARDING"] = ENV['ENABLE_SENSU_SANDBOX_PORT_FORWARDING']
    end 

    
    sandbox.vm.synced_folder "./files", "/vagrant_files"
    sandbox.vm.provision "shell",
      env: envvars,
      path: "./provision/setup.sh"
  end
end
