Vagrant.configure("2") do |config|
  config.vm.define "sensu-classic-sandbox-x86-64", default: true, autostart: true do |sandbox|
    # Bento centos7 box 
    sandbox.vm.box = "bento/centos-7"

    sandbox.vm.hostname = "sensu-classic-sandbox" 

    # Support virtualbox provider
    sandbox.vm.provider "virtualbox" do |vb, vboxoverride|
      vb.cpus = 2
      vb.memory = 2048
      vb.name = "sensu-classic-sandbox-x86-64"
    end
    
    envvars = { }

    # Create forwarded port mapping which allows host access to specific sandbox ports
    if ENV['ENABLE_SENSU_SANDBOX_PORT_FORWRDING'] 
      # Forward Sensu API and redis transport to localhost
      sandbox.vm.network "forwarded_port", guest: 6379, host: 6379
      sandbox.vm.network "forwarded_port", guest: 4567, host: 4567
      # Forward Sensu Dashboard to localhost 3001
      sandbox.vm.network "forwarded_port", guest: 3000, host: 3000
      # Forward Grafana Dashboard to localhost 3001
      sandbox.vm.network "forwarded_port", guest: 4000, host: 4000
      envvars["ENABLE_SENSU_SANDBOX_PORT_FORWRDING"] = ENV['ENABLE_SENSU_SANDBOX_PORT_FORWRDING']
    end 

    # Enterprise
    if ENV['SE_USER'] &&  ENV['SE_PASS']
      envvars["SE_USER"] = ENV['SE_USER']
      envvars["SE_PASS"] = ENV['SE_PASS']
    end 
    
    sandbox.vm.synced_folder "./files", "/vagrant_files"
    sandbox.vm.provision "shell",
      env: envvars,
      path: "./provision/setup.sh"
  end
end
